lightmediascanner: add missing character sets to RDEPENDS
This change fixes the following errors during scanning which produced
invalid id3 results

ERROR: could not add conversion charset 'UTF-16BE': Invalid argument
ERROR: could not add conversion charset 'UTF-16LE': Invalid argument
ERROR: could not add conversion charset 'Latin1': Invalid argument

Bug-AGL: SPEC-1241
Change-Id: I67045575d6d198fb0b767c01701853244361b329
Signed-off-by: Matt Ranostay <matt.ranostay@konsulko.com>